---
title: CS life log
email: csyouk@gmail.com
description: |
  Not a developer. Want to be a hacker.
baseurl: ''
url: csyouk.github.io
github_username: csyouk

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock

paginate: 5
