---
title: CS life log
# email: csyouk@gmail.com
description: |
  Imagineer
baseurl: ''
url: csyouk.github.io
github_username: csyouk

# Build settings
markdown: kramdown
# highlighter: pygments

theme: minima
gems:
  - jekyll-feed
  - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock

paginate: 5
