---
title: CS life log
email: csyouk@gmail.com
description: |
  Not a developer. Want to be a hacker.
baseurl: ''
url: csyouk.github.io
github_username: csyouk
markdown: kramdown
theme: minima
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
